# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/netbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/netbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/netbox.proto\x12\x06netbox\"-\n\x06Target\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x13\n\x0btarget_type\x18\x02 \x01(\t\"\x13\n\x11GetTargetsRequest\"5\n\x12GetTargetsResponse\x12\x1f\n\x07targets\x18\x01 \x03(\x0b\x32\x0e.netbox.Target2M\n\x06NetBox\x12\x43\n\nGetTargets\x12\x19.netbox.GetTargetsRequest\x1a\x1a.netbox.GetTargetsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.netbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGET']._serialized_start=30
  _globals['_TARGET']._serialized_end=75
  _globals['_GETTARGETSREQUEST']._serialized_start=77
  _globals['_GETTARGETSREQUEST']._serialized_end=96
  _globals['_GETTARGETSRESPONSE']._serialized_start=98
  _globals['_GETTARGETSRESPONSE']._serialized_end=151
  _globals['_NETBOX']._serialized_start=153
  _globals['_NETBOX']._serialized_end=230
# @@protoc_insertion_point(module_scope)
