x-build-common: &build_args
  context: .
  dockerfile: Dockerfile
  args:
    CLOUDSMITH_USER: "__token__"
    CLOUDSMITH_TOKEN: ${CLOUDSMITH_TOKEN}

services:
  netbox:
    build: *build_args
    container_name: netbox_grpc
    env_file:
      - .env
    volumes:
      - .:/app
    command: python manage.py workers netbox
    ports:
      - "50051:50051"
    restart: always
    mem_limit: 512m
    mem_reservation: 256m