x-build-common: &build_args
  context: .
  dockerfile: Dockerfile
  args:
    CLOUDSMITH_USER: "__token__"
    CLOUDSMITH_TOKEN: ${CLOUDSMITH_TOKEN}

services:
  api:
    build: *build_args
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    mem_limit: 768m
    mem_reservation: 512m
