openapi: 3.0.3
info:
  title: Discovery Service
  version: "1.0.0"

paths:
  /check:
    post:
      summary: Проверить все устройства
      description: Запускает процесс проверки состояния всех устройств в сети.
      responses:
        "200":
          description: Проверка запущена
          content:
            application/json:
              example:
                status: "started"

  /check/{ip}:
    post:
      summary: Проверить устройство по IP
      description: Проверяет состояние одного устройства.
      parameters:
        - name: ip
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Статус устройства
          content:
            application/json:
              example:
                ip: "10.0.0.5"
                reachable: true

  /last-results:
    get:
      summary: Последние результаты проверки
      description: Возвращает результаты последней проверки устройств.
      responses:
        "200":
          description: Результаты проверки
          content:
            application/json:
              example:
                results:
                  - ip: "10.0.0.5"
                    online: true

  /health:
    get:
      summary: Проверка сервиса
      responses:
        "200":
          description: Сервис работает
          content:
            application/json:
              example:
                status: "ok"

  /metrics:
    get:
      summary: Метрики Prometheus
      responses:
        "200":
          description: Метрики Prometheus
