openapi: 3.0.3
info:
  title: Notification Service
  version: "1.0.0"

paths:
  /send-test:
    post:
      summary: Отправить тестовое уведомление
      responses:
        "200":
          description: Уведомление отправлено
          content:
            application/json:
              example:
                status: "sent"

  /last-alerts:
    get:
      summary: Последние уведомления
      responses:
        "200":
          description: Список уведомлений
          content:
            application/json:
              example:
                alerts:
                  - timestamp: "2025-07-31T09:15:00Z"
                    message: "VLAN mismatch на sw-core-1"

  /health:
    get:
      summary: Проверка сервиса
      responses:
        "200":
          description: Сервис работает
          content:
            application/json:
              example:
                status: "ok"

  /metrics:
    get:
      summary: Метрики Prometheus
      responses:
        "200":
          description: Метрики Prometheus
