# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import netbox_pb2 as proto_dot_netbox__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/netbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NetBoxStub(object):
    """===== gRPC сервис =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTargets = channel.unary_unary(
                '/netbox.NetBox/GetTargets',
                request_serializer=proto_dot_netbox__pb2.GetTargetsRequest.SerializeToString,
                response_deserializer=proto_dot_netbox__pb2.GetTargetsResponse.FromString,
                _registered_method=True)
        self.GetDevices = channel.unary_unary(
                '/netbox.NetBox/GetDevices',
                request_serializer=proto_dot_netbox__pb2.GetDevicesRequest.SerializeToString,
                response_deserializer=proto_dot_netbox__pb2.GetDevicesResponse.FromString,
                _registered_method=True)
        self.GetSubnets = channel.unary_unary(
                '/netbox.NetBox/GetSubnets',
                request_serializer=proto_dot_netbox__pb2.GetSubnetsRequest.SerializeToString,
                response_deserializer=proto_dot_netbox__pb2.GetSubnetsResponse.FromString,
                _registered_method=True)
        self.GetIPs = channel.unary_unary(
                '/netbox.NetBox/GetIPs',
                request_serializer=proto_dot_netbox__pb2.GetIPsRequest.SerializeToString,
                response_deserializer=proto_dot_netbox__pb2.GetIPsResponse.FromString,
                _registered_method=True)


class NetBoxServicer(object):
    """===== gRPC сервис =====

    """

    def GetTargets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubnets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIPs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetBoxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTargets,
                    request_deserializer=proto_dot_netbox__pb2.GetTargetsRequest.FromString,
                    response_serializer=proto_dot_netbox__pb2.GetTargetsResponse.SerializeToString,
            ),
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=proto_dot_netbox__pb2.GetDevicesRequest.FromString,
                    response_serializer=proto_dot_netbox__pb2.GetDevicesResponse.SerializeToString,
            ),
            'GetSubnets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubnets,
                    request_deserializer=proto_dot_netbox__pb2.GetSubnetsRequest.FromString,
                    response_serializer=proto_dot_netbox__pb2.GetSubnetsResponse.SerializeToString,
            ),
            'GetIPs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIPs,
                    request_deserializer=proto_dot_netbox__pb2.GetIPsRequest.FromString,
                    response_serializer=proto_dot_netbox__pb2.GetIPsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netbox.NetBox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netbox.NetBox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NetBox(object):
    """===== gRPC сервис =====

    """

    @staticmethod
    def GetTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netbox.NetBox/GetTargets',
            proto_dot_netbox__pb2.GetTargetsRequest.SerializeToString,
            proto_dot_netbox__pb2.GetTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netbox.NetBox/GetDevices',
            proto_dot_netbox__pb2.GetDevicesRequest.SerializeToString,
            proto_dot_netbox__pb2.GetDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubnets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netbox.NetBox/GetSubnets',
            proto_dot_netbox__pb2.GetSubnetsRequest.SerializeToString,
            proto_dot_netbox__pb2.GetSubnetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIPs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netbox.NetBox/GetIPs',
            proto_dot_netbox__pb2.GetIPsRequest.SerializeToString,
            proto_dot_netbox__pb2.GetIPsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
