# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/netbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/netbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/netbox.proto\x12\x06netbox\"-\n\x06Target\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x13\n\x0btarget_type\x18\x02 \x01(\t\"\x13\n\x11GetTargetsRequest\"5\n\x12GetTargetsResponse\x12\x1f\n\x07targets\x18\x01 \x03(\x0b\x32\x0e.netbox.Target\"C\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\";\n\x06Subnet\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04vlan\x18\x03 \x01(\t\"[\n\tIPAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x10\n\x08\x64ns_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x16\n\x0einterface_name\x18\x04 \x01(\t\"!\n\x11GetDevicesRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\x12GetDevicesResponse\x12\x1f\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0e.netbox.Device\"#\n\x11GetSubnetsRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"5\n\x12GetSubnetsResponse\x12\x1f\n\x07subnets\x18\x01 \x03(\x0b\x32\x0e.netbox.Subnet\" \n\rGetIPsRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"0\n\x0eGetIPsResponse\x12\x1e\n\x03ips\x18\x01 \x03(\x0b\x32\x11.netbox.IPAddress2\x90\x02\n\x06NetBox\x12\x43\n\nGetTargets\x12\x19.netbox.GetTargetsRequest\x1a\x1a.netbox.GetTargetsResponse\x12\x43\n\nGetDevices\x12\x19.netbox.GetDevicesRequest\x1a\x1a.netbox.GetDevicesResponse\x12\x43\n\nGetSubnets\x12\x19.netbox.GetSubnetsRequest\x1a\x1a.netbox.GetSubnetsResponse\x12\x37\n\x06GetIPs\x12\x15.netbox.GetIPsRequest\x1a\x16.netbox.GetIPsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.netbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGET']._serialized_start=30
  _globals['_TARGET']._serialized_end=75
  _globals['_GETTARGETSREQUEST']._serialized_start=77
  _globals['_GETTARGETSREQUEST']._serialized_end=96
  _globals['_GETTARGETSRESPONSE']._serialized_start=98
  _globals['_GETTARGETSRESPONSE']._serialized_end=151
  _globals['_DEVICE']._serialized_start=153
  _globals['_DEVICE']._serialized_end=220
  _globals['_SUBNET']._serialized_start=222
  _globals['_SUBNET']._serialized_end=281
  _globals['_IPADDRESS']._serialized_start=283
  _globals['_IPADDRESS']._serialized_end=374
  _globals['_GETDEVICESREQUEST']._serialized_start=376
  _globals['_GETDEVICESREQUEST']._serialized_end=409
  _globals['_GETDEVICESRESPONSE']._serialized_start=411
  _globals['_GETDEVICESRESPONSE']._serialized_end=464
  _globals['_GETSUBNETSREQUEST']._serialized_start=466
  _globals['_GETSUBNETSREQUEST']._serialized_end=501
  _globals['_GETSUBNETSRESPONSE']._serialized_start=503
  _globals['_GETSUBNETSRESPONSE']._serialized_end=556
  _globals['_GETIPSREQUEST']._serialized_start=558
  _globals['_GETIPSREQUEST']._serialized_end=590
  _globals['_GETIPSRESPONSE']._serialized_start=592
  _globals['_GETIPSRESPONSE']._serialized_end=640
  _globals['_NETBOX']._serialized_start=643
  _globals['_NETBOX']._serialized_end=915
# @@protoc_insertion_point(module_scope)
